export const SN_PURCHASE_ORDER = 'purchaseOrder'
export const PURCHASEORDER_LIST_UPDATED = SN_PURCHASE_ORDER + '/LIST_UPDATED'
export const PURCHASEORDER_CURRENT_UPDATED = SN_PURCHASE_ORDER + '/CURRENT_UPDATED'
